version: '3.6'
services:
  database:
    image: "postgres" # use latest official postgres version
    container_name: "my_postgres"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: mydb
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    ports:
      - 5432:5432
  runenv:
    image: runenv:latest
    container_name: "runenv"
    depends_on:
        - database
    volumes:
      - ./get_data.py:/work/get_data.py
    command: bash -c "sleep infinity"
volumes:
  database-data: # named volumes can be managed easier using docker-compose
